const cuisines = [
  "afghan",
  "albanian",
  "algerian",
  "american",
  "argentinian",
  "armenian",
  "australian",
  "austrian",
  "azerbaijani",
  "BBQ",
  "bangladeshi",
  "belgian",
  "bolivian",
  "brazilian",
  "british",
  "bulgarian",
  "burmese",
  "cambodian",
  "caribbean",
  "chilean",
  "chinese",
  "colombian",
  "croatian",
  "cuban",
  "czech",
  "danish",
  "dominican",
  "dutch",
  "ecuadorian",
  "egyptian",
  "ethiopian",
  "filipino",
  "finnish",
  "french",
  "georgian",
  "german",
  "ghanaian",
  "greek",
  "guatemalan",
  "haitian",
  "hawaiian",
  "honduran",
  "hungarian",
  "icelandic",
  "indian",
  "indonesian",
  "iranian",
  "iraqi",
  "irish",
  "israeli",
  "italian",
  "jamaican",
  "japanese",
  "jordanian",
  "kazakh",
  "kenyan",
  "korean",
  "kuwaiti",
  "kyrgyz",
  "laotian",
  "lebanese",
  "libyan",
  "malaysian",
  "mediterranean",
  "mexican",
  "mongolian",
  "moroccan",
  "nepalese",
  "new zealand",
  "nicaraguan",
  "nigerian",
  "norwegian",
  "pakistani",
  "palestinian",
  "panamanian",
  "paraguayan",
  "peruvian",
  "persian",
  "polish",
  "portuguese",
  "puerto rican",
  "qatari",
  "romanian",
  "russian",
  "saudi",
  "scandinavian",
  "senegalese",
  "serbian",
  "singaporean",
  "slovak",
  "slovenian",
  "somali",
  "south african",
  "spanish",
  "sri lankan",
  "sudanese",
  "swedish",
  "swiss",
  "syrian",
  "taiwanese",
  "tajik",
  "tanzanian",
  "thai",
  "tibetan",
  "tunisian",
  "turkish",
  "ugandan",
  "ukrainian",
  "uruguayan",
  "uzbek",
  "venezuelan",
  "vietnamese",
  "welsh",
  "yemeni",
  "zambian",
  "zimbabwean",
  "tex mex",
  "cajun",
  "creole",
  "fusion",
  "soul food",
  "vegan",
  "vegetarian",
];

bool containsOnlyLetters(String input) {
  final regex = RegExp(r'^[a-zA-Z\s]+$');
  return regex.hasMatch(input);
}

bool validateCuisine(String input) {
  final text = input.toLowerCase().trim();

  if (!RegExp(r'^[a-zA-Z\s]+$').hasMatch(text)) return false;
  if (text.length < 3 || text.length > 30) return false;
  if (!cuisines.contains(text)) return false;

  return true;
}

String inferCuisineTypeFromSuggestion(String input) {
  final text = input.toLowerCase().trim();
  if (cuisines.contains(text)) return text;

  final containsMatch = cuisines.where((c) => text.contains(c)).toList()
    ..sort((a, b) => b.length.compareTo(a.length));
  if (containsMatch.isNotEmpty) return containsMatch.first;

  return 'fusion';
}
